server:
  port: 8013
spring:
  application:
    name: test-produces
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
management:
  endpoints:
    web:
      exposure:
        exclude: '*'

